// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';
export const SET_ESTIMATES_COUNT = 'SET_ESTIMATES_COUNT';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

//Search
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
export const SET_TOTAL_PAGE_AMOUNT = 'SET_TOTAL_PAGE_AMOUNT';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';

//Cart
export const FETCH_ESTIMATES_DATA_START = 'FETCH_ESTIMATES_DATA_START';
export const FETCH_ESTIMATES_DATA_SUCCESS = 'FETCH_ESTIMATES_DATA_SUCCESS';
export const ON_SUBMIT_ESTIMATE_REQUEST_SUCCESS = 'ON_SUBMIT_ESTIMATE_REQUEST_SUCCESS';
export const ON_SUBMIT_ESTIMATE_REQUEST_FAILED = 'ON_SUBMIT_ESTIMATE_REQUEST_FAILED';
export const INIT_QUOTATION_REQIUEST_RESULT = 'INIT_QUOTATION_REQIUEST_RESULT';